from django.conf.urls import patterns, url

urlpatterns = patterns('mob.views',
    url(r'^contact/$', 'contact', name='contact'),
    url(r'^index/$', 'index', name='searchindex'),
    url(r'^login/$',  'login', name='login'),
    url(r'^logout_m/$',  'logout', name='logout'),
    url(r'^register_m/$',  'register', name='register'),
    url(r'^add_favoritebid_m/(?P<objectid>\d+)/$',  'add_favoritebid', name='add_favoritebid'),
    url(r'^add_favoriteplatform_/(?P<objectid>\d+)/$',  'add_favoriteplatform', name='add_favoriteplatform'),
    url(r'^add_reminder_m/(?P<objectid>\d+)/$',  'add_reminder', name='add_reminder'),
    url(r'^del_reminder_m/(?P<objectid>\d+)/$',  'del_reminder', name='del_reminder'),
    url(r'^do_reminder_m/$',  'do_reminder', name='do_reminder'),
    url(r'^myfavorite_m/(?P<tid>\d+)/$$',  'myfavorite', name='myfavorite'),
    url(r'^platform_m/$',  'platform', name='platform'),
    url(r'^userinformation_m/$',  'userinformation', name='userinformation'),
    url(r'^save_filter_m/$',  'save_filter', name='save_filter'),
    url(r'^del_filter_m/(?P<fid>\d+)/$',  'del_filter', name='del_filter'),
    url(r'^bid_detail_m/(?P<objectid>\d+)/$',  'bid_detail', name='bid_detail'),
    url(r'^comb_detail_m/(?P<ids>[^/]+)/$',  'comb_detail', name='comb_detail'),
    url(r'^shortcut_request_m/(?P<objectid>\d+)/$',  'shortcut_request', name='shortcut_request'),
    url(r'getverifycode_m/$', 'verifycode', name='verifycode'),
    url(r'forgetpw_m/$', 'forgetpw', name='forgetpw'),
    # url(r'^other_page_reg/$',  'other_page_reg', name='other_page_reg'),
    # url(r'^other_reg/$',  'other_reg', name='other_reg'),
    url(r'^about_us_m/$',  'about_us', name='about_us'),
    url(r'^contact_us_m/$',  'contact_us', name='contact_us'),
    url(r'^disclaimer_m/$',  'disclaimer', name='disclaimer'),
    url(r'^checkvcode_m/$',  'checkvcode', name='checkvcode'),

     url(r'^checkuser_m/$',  'checkuser', name='checkuser'),
    url(r'^checkuser_phone_m/$',  'checkuser_phone', name='checkuser_phone'),
    url(r'^user_updatepwd_m/$',  'user_updatepwd', name='user_updatepwd'),
    url(r'^phone_infoPage_m/$',  'phone_infoPage', name='phone_infoPage'),
    url(r'^send_smscode_m/$',  'send_smscode', name='send_smscode'),
    url(r'^checksmscode_m/$',  'checksmscode', name='checksmscode'),
    url(r'^safecenter_m/$',  'safecenter', name='safecenter'),
    url(r'^change_phone_number_m/$',  'change_phone_number', name='change_phone_number'),
    url(r'^send_smscode_modify_m/$',  'send_smscode_modify', name='send_smscode_modify'),

)


urlpatterns += patterns('mob.viewss',
    url(r'^qq_is_first_m/$',  'qq_is_first', name='qq_is_first'),
    url(r'^wb_is_first_m/$',  'wb_is_first', name='wb_is_first'),
    url(r'^wx_is_first_m/$',  'wx_is_first', name='wx_is_first'),
    url(r'^wxcheck_m/$',  'wxcheck', name='wxcheck'),
    url(r'^wx_binding_m/$',  'wx_binding', name='wx_binding'),
    url(r'^wx_register_m/$',  'wx_register', name='wx_register'),
    url(r'^ch_access_token_m/$',  'ch_access_token', name='ch_access_token'),
    url(r'^test_thread_m/$',  'remind_thread', name='remind_thread'),
    url(r'^test_thread_on_m/$',  'test_thread_on', name='test_thread_on'),
    url(r'^send_message_m/$',  'send_message', name='send_message'),
    url(r'^wx_bid_detail_m/(?P<objectid>\d+)/$',  'wx_bid_detail', name='wx_bid_detail'),
)